export const PRODUCTS_LIST_INIT = '[PRODUCTS] PRODUCTS_LIST_INIT';
export const PRODUCTS_LIST_SUCCESS = '[PRODUCTS] PRODUCTS_LIST_SUCCESS';
export const PRODUCTS_LIST_ERROR = '[PRODUCTS] PRODUCTS_LIST_ERROR';
export const PRODUCTS_CHANGE_PAGE = '[PRODUCTS] PRODUCTS_CHANGE_PAGE';
