export const ORDERS_LIST_INIT = '[ORDERS] ORDERS_LIST_INIT';
export const ORDER_ADD_SHOPPING_CART_INIT = '[ORDERS] ORDER_ADD_SHOPPING_CART_INIT';
export const ORDER_UPDATE_UNITS_SHOPPING_CART_INIT = '[ORDERS] ORDER_UPDATE_UNITS_SHOPPING_CART_INIT';
export const ORDER_CREATE_INIT = '[ORDERS] ORDER_CREATE_INIT';
export const ORDER_CREATE_SUCCESS = '[ORDERS] ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_ERROR = '[ORDERS] ORDER_CREATE_ERROR';
export const ORDER_DELETE_INIT = '[ORDERS] ORDER_DELETE_INIT';
