export const USER_CREATE_INIT = '[USERS] USER_CREATE_INIT';
export const USER_CREATE_SUCCESS = '[USERS] USER_CREATE_SUCCESS';
export const USER_CREATE_ERROR = '[USERS] USER_CREATE_ERROR';
export const USER_ME_INIT = '[USERS] USER_ME_INIT';
export const USER_ME_SUCCESS = '[USERS] USER_ME_SUCCESS';
export const USER_ME_ERROR = '[USERS] USER_ME_ERROR';
export const USER_FORM_CUSTOMER_FIELD_CHANGE = '[USERS] USER_FORM_CUSTOMER_FIELD_CHANGE';
